# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-02 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygallery.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='email',
        ),
        migrations.RemoveField(
            model_name='image',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='last_name',
        ),
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(to='mygallery.Location'),
        ),
    ]
