# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-02 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_auto_20200302_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='first_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='email',
        ),
        migrations.RemoveField(
            model_name='location',
            name='images',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone_number',
        ),
    ]
