# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-03 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0004_auto_20200302_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
