# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0006_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='ret/'),
        ),
    ]
