# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-03 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0008_auto_20200303_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
